import type { ClusterOverview, NodeInfo } from '../types/cluster';

/**
 * Synthetic but structurally faithful overviews, used to develop and review the
 * visual layer without pointing the app at a real cluster. They deliberately cover
 * the awkward cases: an unready node, memory pressure, a cordon, a Spot-heavy
 * fleet, kubelet skew, overcommitted limits, and long resource names.
 *
 * Two providers are represented so the provider-agnostic paths stay honest: an
 * EKS cluster with full AWS enrichment, and an AKS cluster with none of it.
 */

const GI = 1024 ** 3;

function taint(key: string, value: string | undefined, effect: string) {
  return { key, value, effect, label: value ? `${key}=${value}:${effect}` : `${key}:${effect}` };
}

function node(overrides: Partial<NodeInfo> & Pick<NodeInfo, 'name'>): NodeInfo {
  return {
    ready: true,
    health: 'good',
    roles: ['worker'],
    kubelet_version: 'v1.30.4-eks-a1b2c3',
    kubelet_minor: 30,
    instance_type: 'm6i.2xlarge',
    capacity_type: 'ON_DEMAND',
    node_pool: 'ng-general-a',
    zone: 'sa-east-1a',
    architecture: 'amd64',
    os_image: 'Amazon Linux 2023.5.20240903',
    container_runtime: 'containerd://1.7.20',
    age: '23d',
    cpu_allocatable_milli: 7910,
    cpu_requested_milli: 4200,
    cpu_limit_milli: 9600,
    cpu_used_milli: 3100,
    memory_allocatable_bytes: 30 * GI,
    memory_requested_bytes: 18 * GI,
    memory_limit_bytes: 34 * GI,
    memory_used_bytes: 14 * GI,
    pod_count: 24,
    pod_capacity: 58,
    conditions: [
      { kind: 'Ready', status: 'True', reason: 'KubeletReady', healthy: true },
      { kind: 'MemoryPressure', status: 'False', reason: 'KubeletHasSufficientMemory', healthy: true },
      { kind: 'DiskPressure', status: 'False', reason: 'KubeletHasNoDiskPressure', healthy: true },
      { kind: 'PIDPressure', status: 'False', reason: 'KubeletHasSufficientPID', healthy: true },
    ],
    taints: [],
    pressure_reasons: [],
    pressure: false,
    unschedulable: false,
    pods: Array.from({ length: 6 }, (_, index) => ({
      name: `checkout-api-7d9f8b6c4d-${index}kx2m`,
      namespace: index % 2 === 0 ? 'payments' : 'kube-system',
      status: 'Running',
      restarts: index,
      cpu_requested_milli: 250 + index * 90,
      memory_requested_bytes: (0.5 + index * 0.4) * GI,
    })),
    ...overrides,
  };
}

export const awsFixture: ClusterOverview = {
  context: 'arn:aws:eks:sa-east-1:123456789012:cluster/prod-shark',
  generated_at: new Date(Date.now() - 42_000).toISOString(),
  control_plane: {
    provider: 'eks',
    distribution: 'Amazon EKS',
    endpoint: 'https://A1B2C3D4E5F6A7B8C9D0.gr7.sa-east-1.eks.amazonaws.com',
    kubernetes_version: 'v1.30.4-eks-a1b2c3',
    control_plane_minor: 30,
    cluster_name: 'prod-shark',
    region: 'sa-east-1',
    account_id: '123456789012',
    account_label: 'Account',
    provider_status: 'ACTIVE',
    provider_version: 'eks.7',
    oidc_issuer: 'https://oidc.eks.sa-east-1.amazonaws.com/id/A1B2C3D4E5F6',
    metrics_available: true,
  },
  health: {
    score: 71,
    grade: 'Degraded',
    headline: 'Multiple subsystems are impaired. Investigate the findings below.',
    signals: [
      { name: 'Node readiness', score: 86, weight: 25, detail: '6 of 7 nodes report Ready', severity: 'warning' },
      { name: 'Node conditions', score: 71, weight: 10, detail: '2 node(s) under pressure or cordoned', severity: 'serious' },
      { name: 'Version alignment', score: 86, weight: 5, detail: '1 node(s) run a kubelet minor other than 1.30', severity: 'warning' },
      { name: 'Pod readiness', score: 92, weight: 25, detail: '162 of 176 non-completed pods are Ready', severity: 'good' },
      { name: 'Container stability', score: 41, weight: 15, detail: '4 pod(s) in a crash or image-pull state', severity: 'critical' },
      { name: 'Scheduling headroom', score: 48, weight: 15, detail: '88% of allocatable capacity is already requested', severity: 'critical' },
      { name: 'Workload availability', score: 94, weight: 5, detail: '3 of 52 controllers are below desired replicas', severity: 'good' },
    ],
  },
  capacity: {
    cpu: { allocatable: 55_370, requested: 48_600, limits: 71_200, used: 24_800 },
    memory: { allocatable: 210 * GI, requested: 168 * GI, limits: 264 * GI, used: 121 * GI },
    pod_slots: { used: 176, allocatable: 406 },
  },
  nodes: [
    node({ name: 'ip-10-0-12-34.sa-east-1.compute.internal' }),
    node({
      name: 'ip-10-0-12-88.sa-east-1.compute.internal',
      ready: false,
      health: 'critical',
      cpu_used_milli: undefined,
      memory_used_bytes: undefined,
      conditions: [
        { kind: 'Ready', status: 'Unknown', reason: 'NodeStatusUnknown', message: 'Kubelet stopped posting node status.', healthy: false },
        { kind: 'MemoryPressure', status: 'Unknown', healthy: false },
      ],
      pressure: true,
      pressure_reasons: ['MemoryPressure'],
      // A node the control plane has given up on carries the standard eviction taints.
      taints: [
        taint('node.kubernetes.io/unreachable', undefined, 'NoExecute'),
        taint('node.kubernetes.io/unreachable', undefined, 'NoSchedule'),
        taint('node.kubernetes.io/memory-pressure', undefined, 'NoSchedule'),
      ],
      pods: [],
      pod_count: 0,
    }),
    node({
      name: 'ip-10-0-31-207.sa-east-1.compute.internal',
      zone: 'sa-east-1b',
      health: 'serious',
      pressure: true,
      pressure_reasons: ['DiskPressure'],
      capacity_type: 'SPOT',
      instance_type: 'm6i.4xlarge',
      node_pool: 'ng-spot-b',
      taints: [
        taint('workload', 'batch', 'NoSchedule'),
        taint('nvidia.com/gpu', 'present', 'NoSchedule'),
        taint('spot-instance', 'true', 'PreferNoSchedule'),
      ],
      cpu_allocatable_milli: 15_890,
      cpu_requested_milli: 14_100,
      cpu_limit_milli: 19_200,
      cpu_used_milli: 12_400,
      memory_allocatable_bytes: 62 * GI,
      memory_requested_bytes: 55 * GI,
      memory_limit_bytes: 71 * GI,
      memory_used_bytes: 48 * GI,
      pod_count: 41,
      pod_capacity: 110,
    }),
    node({
      name: 'ip-10-0-31-19.sa-east-1.compute.internal',
      zone: 'sa-east-1b',
      health: 'warning',
      unschedulable: true,
      capacity_type: 'SPOT',
      node_pool: 'ng-spot-b',
      kubelet_version: 'v1.29.8-eks-a1b2c3',
      kubelet_minor: 29,
      cpu_used_milli: 900,
    }),
    node({ name: 'ip-10-0-52-9.sa-east-1.compute.internal', zone: 'sa-east-1c', capacity_type: 'SPOT', node_pool: 'ng-spot-c' }),
    node({ name: 'ip-10-0-52-140.sa-east-1.compute.internal', zone: 'sa-east-1c', capacity_type: 'SPOT', node_pool: 'ng-spot-c', instance_type: 'c6i.xlarge' }),
    node({ name: 'ip-10-0-12-201.sa-east-1.compute.internal', instance_type: 'r6i.2xlarge', node_pool: 'ng-memory-a' }),
  ],
  pods: {
    total: 183,
    running: 168,
    ready: 162,
    pending: 6,
    failed: 2,
    succeeded: 7,
    unknown: 0,
    total_restarts: 214,
    by_phase: [
      { label: 'Running', value: 168 },
      { label: 'Pending', value: 6 },
      { label: 'Succeeded', value: 7 },
      { label: 'Failed', value: 2 },
    ],
    by_namespace: [
      { label: 'kube-system', value: 48 },
      { label: 'payments', value: 37 },
      { label: 'checkout', value: 29 },
      { label: 'observability', value: 24 },
      { label: 'ingress-nginx', value: 12 },
    ],
    problems: [
      { name: 'ledger-reconciler-6d4b9c7f8d-2xk9p', namespace: 'payments', node: 'ip-10-0-31-207.sa-east-1.compute.internal', phase: 'Running', reason: 'CrashLoopBackOff', message: 'back-off 5m0s restarting failed container', restarts: 87, age: '3h', severity: 'critical' },
      { name: 'fraud-scoring-58f7c6d9b4-lm3nq', namespace: 'payments', node: 'ip-10-0-12-34.sa-east-1.compute.internal', phase: 'Pending', reason: 'ImagePullBackOff', message: 'Back-off pulling image "registry.internal/fraud:2.14.0"', restarts: 0, age: '22m', severity: 'critical' },
      { name: 'batch-export-29187360-8kxv2', namespace: 'checkout', node: undefined, phase: 'Pending', reason: 'Pending', message: 'The pod has not been scheduled or its containers have not started.', restarts: 0, age: '14m', severity: 'serious' },
      { name: 'otel-collector-9f8d7c6b5a-qq41z', namespace: 'observability', node: 'ip-10-0-52-9.sa-east-1.compute.internal', phase: 'Running', reason: 'Restarts', restarts: 12, age: '6d', severity: 'serious' },
    ],
    top_restarts: [
      { name: 'ledger-reconciler-6d4b9c7f8d-2xk9p', namespace: 'payments', phase: 'Running', reason: 'Restarts', restarts: 87, age: '3h', severity: 'critical' },
      { name: 'otel-collector-9f8d7c6b5a-qq41z', namespace: 'observability', phase: 'Running', reason: 'Restarts', restarts: 12, age: '6d', severity: 'critical' },
      { name: 'checkout-api-7d9f8b6c4d-5kx2m', namespace: 'checkout', phase: 'Running', reason: 'Restarts', restarts: 6, age: '2d', severity: 'serious' },
    ],
    top_cpu: [
      { name: 'fraud-scoring-58f7c6d9b4-w8ptr', namespace: 'payments', cpu_used_milli: 3820, cpu_requested_milli: 2000 },
      { name: 'checkout-api-7d9f8b6c4d-5kx2m', namespace: 'checkout', cpu_used_milli: 2140, cpu_requested_milli: 2500 },
      { name: 'prometheus-server-0', namespace: 'observability', cpu_used_milli: 1890, cpu_requested_milli: 1000 },
      { name: 'ledger-reconciler-6d4b9c7f8d-2xk9p', namespace: 'payments', cpu_used_milli: 1240, cpu_requested_milli: 500 },
      { name: 'ingress-nginx-controller-6c9d8f7b5a-mn2kq', namespace: 'ingress-nginx', cpu_used_milli: 760, cpu_requested_milli: 500 },
      { name: 'coredns-5d78c9869d-vv8lp', namespace: 'kube-system', cpu_used_milli: 145, cpu_requested_milli: 100 },
    ],
  },
  workloads: {
    deployments: { total: 38, degraded: 2 },
    statefulsets: { total: 6, degraded: 1 },
    daemonsets: { total: 8, degraded: 0 },
    degraded: [
      { kind: 'Deployment', namespace: 'payments', name: 'fraud-scoring', ready: 1, desired: 4 },
      { kind: 'StatefulSet', namespace: 'observability', name: 'prometheus-server', ready: 1, desired: 2 },
      { kind: 'Deployment', namespace: 'checkout', name: 'batch-export', ready: 2, desired: 3 },
    ],
  },
  distribution: {
    zones: [
      { zone: 'sa-east-1a', nodes: 3, ready_nodes: 2, pods: 54, cpu_allocatable_milli: 23_730, memory_allocatable_bytes: 90 * GI },
      { zone: 'sa-east-1b', nodes: 2, ready_nodes: 2, pods: 65, cpu_allocatable_milli: 23_800, memory_allocatable_bytes: 92 * GI },
      { zone: 'sa-east-1c', nodes: 2, ready_nodes: 2, pods: 57, cpu_allocatable_milli: 15_820, memory_allocatable_bytes: 60 * GI },
    ],
    instance_types: [
      { label: 'm6i.2xlarge', value: 3 },
      { label: 'm6i.4xlarge', value: 1 },
      { label: 'c6i.xlarge', value: 1 },
      { label: 'r6i.2xlarge', value: 1 },
    ],
    capacity_types: [
      { label: 'SPOT', value: 4 },
      { label: 'ON_DEMAND', value: 3 },
    ],
    node_pools: [
      { label: 'ng-spot-b', value: 2 },
      { label: 'ng-spot-c', value: 2 },
      { label: 'ng-general-a', value: 2 },
      { label: 'ng-memory-a', value: 1 },
    ],
    taints: [
      { label: 'workload=batch:NoSchedule', value: 1 },
      { label: 'nvidia.com/gpu=present:NoSchedule', value: 1 },
      { label: 'spot-instance=true:PreferNoSchedule', value: 1 },
      { label: 'node.kubernetes.io/unreachable:NoExecute', value: 1 },
      { label: 'node.kubernetes.io/unreachable:NoSchedule', value: 1 },
      { label: 'node.kubernetes.io/memory-pressure:NoSchedule', value: 1 },
    ],
    kubelet_versions: [
      { label: 'v1.30.4-eks-a1b2c3', value: 6 },
      { label: 'v1.29.8-eks-a1b2c3', value: 1 },
    ],
  },
  events: {
    warning_count: 341,
    truncated: false,
    by_reason: [
      { label: 'BackOff', value: 142 },
      { label: 'FailedScheduling', value: 81 },
      { label: 'Unhealthy', value: 54 },
      { label: 'FailedMount', value: 31 },
      { label: 'NodeNotReady', value: 18 },
      { label: 'FailedCreatePodSandBox', value: 15 },
    ],
    recent: [],
  },
  findings: [
    {
      severity: 'critical',
      title: 'Nodes are not Ready',
      detail: 'The kubelet on these nodes is not reporting Ready, so their pods may already be evicted or stuck.',
      count: 1,
      targets: ['ip-10-0-12-88.sa-east-1.compute.internal'],
      hint: 'Check kubelet and CNI health on the node, then the underlying instance status checks.',
    },
    {
      severity: 'critical',
      title: 'Pods are crash-looping or cannot start',
      detail: 'These containers never reached a running state. The reason column is the container’s own status, not an inference.',
      count: 2,
      targets: ['payments/ledger-reconciler-6d4b9c7f8d-2xk9p — CrashLoopBackOff', 'payments/fraud-scoring-58f7c6d9b4-lm3nq — ImagePullBackOff'],
      hint: 'Read the container logs with --previous, then verify the image tag, the mounted config, and the probe thresholds.',
    },
    {
      severity: 'serious',
      title: 'Nodes report resource pressure',
      detail: 'Memory, disk, or PID pressure causes the kubelet to evict pods and refuse new ones.',
      count: 2,
      targets: ['ip-10-0-12-88.sa-east-1.compute.internal (MemoryPressure)', 'ip-10-0-31-207.sa-east-1.compute.internal (DiskPressure)'],
      hint: 'Free disk on the node, raise requests so the scheduler packs less densely, or scale the node pool out.',
    },
    {
      severity: 'warning',
      title: 'Scheduling headroom is low',
      detail: '88% of allocatable CPU and 80% of allocatable memory are already reserved by requests.',
      count: 1,
      targets: [],
      hint: 'Requests reserve capacity whether or not it is used. Right-size requests before adding nodes.',
    },
    {
      severity: 'warning',
      title: 'Kubelet version skew',
      detail: 'Some nodes do not run kubelet 1.30. Kubernetes supports only a bounded skew below the control plane.',
      count: 1,
      targets: ['ip-10-0-31-19.sa-east-1.compute.internal (v1.29.8-eks-a1b2c3)'],
      hint: 'Roll the node pool to the image matching the control plane minor version.',
    },
  ],
  degraded_collectors: [],
};

/**
 * The same page on AKS: no cloud enrichment (no platform version, status, OIDC,
 * or account), Azure node-pool and Spot labels, and no metrics-server — which is
 * the combination most likely to expose a provider-specific assumption.
 */
export const azureFixture: ClusterOverview = {
  ...awsFixture,
  context: 'aks-prod-shark',
  control_plane: {
    provider: 'aks',
    distribution: 'Azure AKS',
    endpoint: 'https://prod-shark-dns-a1b2c3d4.hcp.brazilsouth.azmk8s.io:443',
    kubernetes_version: 'v1.29.9',
    control_plane_minor: 29,
    region: 'brazilsouth',
    account_label: 'Subscription',
    metrics_available: false,
  },
  health: {
    score: 93,
    grade: 'Healthy',
    headline: 'The cluster is operating within normal parameters.',
    signals: [
      { name: 'Node readiness', score: 100, weight: 25, detail: '4 of 4 nodes report Ready', severity: 'good' },
      { name: 'Node conditions', score: 100, weight: 10, detail: 'No node reports pressure or is cordoned', severity: 'good' },
      { name: 'Version alignment', score: 100, weight: 5, detail: 'All kubelets match control plane 1.29', severity: 'good' },
      { name: 'Pod readiness', score: 98, weight: 25, detail: '84 of 86 non-completed pods are Ready', severity: 'good' },
      { name: 'Container stability', score: 100, weight: 15, detail: 'No pod is crash-looping or failing to pull (3 restarts total)', severity: 'good' },
      { name: 'Scheduling headroom', score: 64, weight: 15, detail: '84% of allocatable capacity is already requested', severity: 'serious' },
      { name: 'Workload availability', score: 100, weight: 5, detail: 'All 31 workload controllers are at their desired replica count', severity: 'good' },
    ],
  },
  capacity: {
    cpu: { allocatable: 15_640, requested: 13_100, limits: 18_400, used: undefined },
    memory: { allocatable: 56 * GI, requested: 41 * GI, limits: 62 * GI, used: undefined },
    pod_slots: { used: 86, allocatable: 440 },
  },
  pods: {
    total: 93,
    running: 84,
    ready: 84,
    pending: 2,
    failed: 0,
    succeeded: 7,
    unknown: 0,
    total_restarts: 3,
    by_phase: [
      { label: 'Running', value: 84 },
      { label: 'Succeeded', value: 7 },
      { label: 'Pending', value: 2 },
    ],
    by_namespace: [
      { label: 'kube-system', value: 41 },
      { label: 'payments', value: 28 },
      { label: 'observability', value: 15 },
      { label: 'ingress-nginx', value: 9 },
    ],
    problems: [
      { name: 'batch-export-29187360-8kxv2', namespace: 'checkout', node: undefined, phase: 'Pending', reason: 'Pending', message: 'The pod has not been scheduled or its containers have not started.', restarts: 0, age: '9m', severity: 'serious' },
    ],
    top_restarts: [
      { name: 'konnectivity-agent-6b8f9c7d4e-nn21k', namespace: 'kube-system', phase: 'Running', reason: 'Restarts', restarts: 2, age: '11d', severity: 'warning' },
      { name: 'coredns-autoscaler-7d9c8b6a5f-pp83m', namespace: 'kube-system', phase: 'Running', reason: 'Restarts', restarts: 1, age: '11d', severity: 'warning' },
    ],
    top_cpu: [],
  },
  workloads: {
    deployments: { total: 22, degraded: 0 },
    statefulsets: { total: 3, degraded: 0 },
    daemonsets: { total: 6, degraded: 0 },
    degraded: [],
  },
  nodes: [
    node({
      name: 'aks-systempool-41928374-vmss000000',
      zone: 'brazilsouth-1',
      instance_type: 'Standard_D4s_v5',
      node_pool: 'systempool',
      os_image: 'Ubuntu 22.04.5 LTS',
      kubelet_version: 'v1.29.9',
      kubelet_minor: 29,
      roles: ['agent'],
      cpu_used_milli: undefined,
      memory_used_bytes: undefined,
      cpu_allocatable_milli: 3860,
      memory_allocatable_bytes: 14 * GI,
      cpu_requested_milli: 3200,
      memory_requested_bytes: 10 * GI,
      pod_count: 22,
      pod_capacity: 110,
    }),
    node({
      name: 'aks-userpool-41928374-vmss000001',
      zone: 'brazilsouth-2',
      instance_type: 'Standard_D4s_v5',
      node_pool: 'userpool',
      os_image: 'Ubuntu 22.04.5 LTS',
      kubelet_version: 'v1.29.9',
      kubelet_minor: 29,
      roles: ['agent'],
      cpu_used_milli: undefined,
      memory_used_bytes: undefined,
      cpu_allocatable_milli: 3860,
      memory_allocatable_bytes: 14 * GI,
      cpu_requested_milli: 3400,
      memory_requested_bytes: 11 * GI,
      pod_count: 24,
      pod_capacity: 110,
    }),
    node({
      name: 'aks-spotpool-41928374-vmss000002',
      zone: 'brazilsouth-3',
      instance_type: 'Standard_D8s_v5',
      node_pool: 'spotpool',
      capacity_type: 'SPOT',
      os_image: 'Ubuntu 22.04.5 LTS',
      kubelet_version: 'v1.29.9',
      kubelet_minor: 29,
      roles: ['agent'],
      taints: [taint('kubernetes.azure.com/scalesetpriority', 'spot', 'NoSchedule')],
      cpu_used_milli: undefined,
      memory_used_bytes: undefined,
      cpu_allocatable_milli: 7820,
      memory_allocatable_bytes: 28 * GI,
      cpu_requested_milli: 6500,
      memory_requested_bytes: 20 * GI,
      pod_count: 40,
      pod_capacity: 220,
    }),
  ],
  distribution: {
    zones: [
      { zone: 'brazilsouth-1', nodes: 1, ready_nodes: 1, pods: 22, cpu_allocatable_milli: 3860, memory_allocatable_bytes: 14 * GI },
      { zone: 'brazilsouth-2', nodes: 1, ready_nodes: 1, pods: 24, cpu_allocatable_milli: 3860, memory_allocatable_bytes: 14 * GI },
      { zone: 'brazilsouth-3', nodes: 1, ready_nodes: 1, pods: 40, cpu_allocatable_milli: 7820, memory_allocatable_bytes: 28 * GI },
    ],
    instance_types: [
      { label: 'Standard_D4s_v5', value: 2 },
      { label: 'Standard_D8s_v5', value: 1 },
    ],
    capacity_types: [
      { label: 'ON_DEMAND', value: 2 },
      { label: 'SPOT', value: 1 },
    ],
    node_pools: [
      { label: 'systempool', value: 1 },
      { label: 'userpool', value: 1 },
      { label: 'spotpool', value: 1 },
    ],
    taints: [{ label: 'kubernetes.azure.com/scalesetpriority=spot:NoSchedule', value: 1 }],
    kubelet_versions: [{ label: 'v1.29.9', value: 3 }],
  },
  events: {
    warning_count: 12,
    truncated: false,
    by_reason: [
      { label: 'FailedScheduling', value: 7 },
      { label: 'Unhealthy', value: 5 },
    ],
    recent: [],
  },
  findings: [
    {
      severity: 'warning',
      title: 'Scheduling headroom is low',
      detail: '84% of allocatable CPU and 73% of allocatable memory are already reserved by requests.',
      count: 1,
      targets: [],
      hint: 'Requests reserve capacity whether or not it is used. Right-size requests before adding nodes.',
    },
  ],
  degraded_collectors: [
    'metrics-server is unavailable, so live CPU/memory usage is not shown. Requests and limits are still exact.',
  ],
};
